-- Esquema inicial del editor BPMN multiempresa.
-- Flyway aplica esta migracion de forma atomica en PostgreSQL.

CREATE TABLE empresa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nit VARCHAR(30) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    correo_contacto VARCHAR(254) NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_empresa_nit UNIQUE (nit),
    CONSTRAINT ck_empresa_nit_no_vacio CHECK (btrim(nit) <> ''),
    CONSTRAINT ck_empresa_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_empresa_correo_no_vacio CHECK (btrim(correo_contacto) <> '')
);

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    email VARCHAR(254) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    rol_acceso VARCHAR(30) NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_usuario_empresa FOREIGN KEY (empresa_id)
        REFERENCES empresa (id) ON DELETE CASCADE,
    CONSTRAINT ck_usuario_email_no_vacio CHECK (btrim(email) <> ''),
    CONSTRAINT ck_usuario_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_usuario_apellido_no_vacio CHECK (btrim(apellido) <> ''),
    CONSTRAINT ck_usuario_password_hash_no_vacio CHECK (btrim(password_hash) <> ''),
    CONSTRAINT ck_usuario_rol_acceso CHECK (
        rol_acceso IN ('ADMINISTRADOR', 'EDITOR', 'SOLO_LECTURA')
    )
);

CREATE UNIQUE INDEX uk_usuario_email_ci ON usuario (lower(email));
CREATE INDEX ix_usuario_empresa ON usuario (empresa_id);

CREATE TABLE rol_proceso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(500),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_rol_proceso_empresa FOREIGN KEY (empresa_id)
        REFERENCES empresa (id) ON DELETE CASCADE,
    CONSTRAINT ck_rol_proceso_nombre_no_vacio CHECK (btrim(nombre) <> '')
);

CREATE UNIQUE INDEX uk_rol_proceso_empresa_nombre_ci
    ON rol_proceso (empresa_id, lower(nombre));
CREATE INDEX ix_rol_proceso_empresa ON rol_proceso (empresa_id);

CREATE TABLE proceso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_proceso_empresa FOREIGN KEY (empresa_id)
        REFERENCES empresa (id) ON DELETE CASCADE,
    CONSTRAINT ck_proceso_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_proceso_descripcion_no_vacia CHECK (btrim(descripcion) <> ''),
    CONSTRAINT ck_proceso_categoria_no_vacia CHECK (btrim(categoria) <> ''),
    CONSTRAINT ck_proceso_estado CHECK (estado IN ('BORRADOR', 'PUBLICADO')),
    CONSTRAINT ck_proceso_fechas CHECK (fecha_actualizacion >= fecha_creacion),
    CONSTRAINT uk_proceso_id_empresa UNIQUE (id, empresa_id)
);

CREATE UNIQUE INDEX uk_proceso_empresa_nombre_ci
    ON proceso (empresa_id, lower(nombre));
CREATE INDEX ix_proceso_empresa ON proceso (empresa_id);

CREATE TABLE historial_proceso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    accion VARCHAR(50) NOT NULL,
    detalle TEXT,
    fecha TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_historial_proceso FOREIGN KEY (proceso_id)
        REFERENCES proceso (id) ON DELETE CASCADE,
    CONSTRAINT fk_historial_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id) ON DELETE RESTRICT,
    CONSTRAINT ck_historial_accion_no_vacia CHECK (btrim(accion) <> '')
);

CREATE INDEX ix_historial_proceso_fecha
    ON historial_proceso (proceso_id, fecha DESC);
CREATE INDEX ix_historial_usuario ON historial_proceso (usuario_id);

CREATE TABLE proceso_compartido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id BIGINT NOT NULL,
    empresa_invitada_id BIGINT NOT NULL,
    autorizado_por_id BIGINT NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_compartido_proceso FOREIGN KEY (proceso_id)
        REFERENCES proceso (id) ON DELETE CASCADE,
    CONSTRAINT fk_compartido_empresa_invitada FOREIGN KEY (empresa_invitada_id)
        REFERENCES empresa (id) ON DELETE CASCADE,
    CONSTRAINT fk_compartido_autorizado_por FOREIGN KEY (autorizado_por_id)
        REFERENCES usuario (id) ON DELETE RESTRICT,
    CONSTRAINT uk_compartido_proceso_empresa
        UNIQUE (proceso_id, empresa_invitada_id)
);

CREATE INDEX ix_compartido_empresa_invitada
    ON proceso_compartido (empresa_invitada_id);

CREATE TABLE pool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id BIGINT NOT NULL,
    empresa_participante_id BIGINT,
    nombre VARCHAR(150) NOT NULL,
    tipo_participante VARCHAR(50) NOT NULL,
    canal_externo VARCHAR(100),
    caja_negra BOOLEAN NOT NULL DEFAULT FALSE,
    orden INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_pool_proceso FOREIGN KEY (proceso_id)
        REFERENCES proceso (id) ON DELETE CASCADE,
    CONSTRAINT fk_pool_empresa_participante FOREIGN KEY (empresa_participante_id)
        REFERENCES empresa (id) ON DELETE RESTRICT,
    CONSTRAINT ck_pool_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_pool_tipo_no_vacio CHECK (btrim(tipo_participante) <> ''),
    CONSTRAINT ck_pool_orden_positivo CHECK (orden >= 0),
    CONSTRAINT uk_pool_id_proceso UNIQUE (id, proceso_id),
    CONSTRAINT uk_pool_proceso_orden UNIQUE (proceso_id, orden)
);

CREATE INDEX ix_pool_proceso ON pool (proceso_id);
CREATE INDEX ix_pool_empresa_participante ON pool (empresa_participante_id);

CREATE TABLE lane (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pool_id BIGINT NOT NULL,
    rol_proceso_id BIGINT NOT NULL,
    orden INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_lane_pool FOREIGN KEY (pool_id)
        REFERENCES pool (id) ON DELETE CASCADE,
    CONSTRAINT fk_lane_rol_proceso FOREIGN KEY (rol_proceso_id)
        REFERENCES rol_proceso (id) ON DELETE RESTRICT,
    CONSTRAINT ck_lane_orden_positivo CHECK (orden >= 0),
    CONSTRAINT uk_lane_id_pool UNIQUE (id, pool_id),
    CONSTRAINT uk_lane_pool_orden UNIQUE (pool_id, orden),
    CONSTRAINT uk_lane_pool_rol UNIQUE (pool_id, rol_proceso_id)
);

CREATE INDEX ix_lane_pool ON lane (pool_id);
CREATE INDEX ix_lane_rol_proceso ON lane (rol_proceso_id);

CREATE TABLE pool_rol_disponible (
    pool_id BIGINT NOT NULL,
    rol_proceso_id BIGINT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_pool_rol_disponible PRIMARY KEY (pool_id, rol_proceso_id),
    CONSTRAINT fk_pool_rol_pool FOREIGN KEY (pool_id)
        REFERENCES pool (id) ON DELETE CASCADE,
    CONSTRAINT fk_pool_rol_rol FOREIGN KEY (rol_proceso_id)
        REFERENCES rol_proceso (id) ON DELETE CASCADE
);

CREATE INDEX ix_pool_rol_rol_proceso
    ON pool_rol_disponible (rol_proceso_id);

CREATE TABLE permiso_pool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pool_id BIGINT NOT NULL,
    rol_acceso VARCHAR(30) NOT NULL,
    puede_crear BOOLEAN NOT NULL DEFAULT FALSE,
    puede_editar BOOLEAN NOT NULL DEFAULT FALSE,
    puede_eliminar BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_permiso_pool FOREIGN KEY (pool_id)
        REFERENCES pool (id) ON DELETE CASCADE,
    CONSTRAINT ck_permiso_pool_rol_acceso CHECK (
        rol_acceso IN ('ADMINISTRADOR', 'EDITOR', 'SOLO_LECTURA')
    ),
    CONSTRAINT ck_permiso_solo_lectura CHECK (
        rol_acceso <> 'SOLO_LECTURA'
        OR (NOT puede_crear AND NOT puede_editar AND NOT puede_eliminar)
    ),
    CONSTRAINT uk_permiso_pool_rol UNIQUE (pool_id, rol_acceso)
);

CREATE INDEX ix_permiso_pool ON permiso_pool (pool_id);

CREATE TABLE elemento_proceso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id BIGINT NOT NULL,
    pool_id BIGINT NOT NULL,
    lane_id BIGINT,
    nombre VARCHAR(150) NOT NULL,
    posicion_x NUMERIC(12, 2) NOT NULL,
    posicion_y NUMERIC(12, 2) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_elemento_proceso FOREIGN KEY (proceso_id)
        REFERENCES proceso (id) ON DELETE CASCADE,
    CONSTRAINT fk_elemento_pool_proceso FOREIGN KEY (pool_id, proceso_id)
        REFERENCES pool (id, proceso_id) ON DELETE CASCADE,
    CONSTRAINT fk_elemento_lane_pool FOREIGN KEY (lane_id, pool_id)
        REFERENCES lane (id, pool_id) ON DELETE RESTRICT,
    CONSTRAINT ck_elemento_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT uk_elemento_id_proceso_pool UNIQUE (id, proceso_id, pool_id)
);

CREATE INDEX ix_elemento_proceso ON elemento_proceso (proceso_id);
CREATE INDEX ix_elemento_pool ON elemento_proceso (pool_id);
CREATE INDEX ix_elemento_lane ON elemento_proceso (lane_id);

CREATE TABLE actividad (
    elemento_id BIGINT PRIMARY KEY,
    tipo_actividad VARCHAR(50) NOT NULL,
    CONSTRAINT fk_actividad_elemento FOREIGN KEY (elemento_id)
        REFERENCES elemento_proceso (id) ON DELETE CASCADE,
    CONSTRAINT ck_actividad_tipo_no_vacio CHECK (btrim(tipo_actividad) <> '')
);

CREATE TABLE evento (
    elemento_id BIGINT PRIMARY KEY,
    tipo_evento VARCHAR(50) NOT NULL,
    disparador VARCHAR(50) NOT NULL,
    origen_externo BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_evento_elemento FOREIGN KEY (elemento_id)
        REFERENCES elemento_proceso (id) ON DELETE CASCADE,
    CONSTRAINT ck_evento_tipo_no_vacio CHECK (btrim(tipo_evento) <> ''),
    CONSTRAINT ck_evento_disparador_no_vacio CHECK (btrim(disparador) <> '')
);

CREATE TABLE gateway (
    elemento_id BIGINT PRIMARY KEY,
    tipo_gateway VARCHAR(20) NOT NULL,
    CONSTRAINT fk_gateway_elemento FOREIGN KEY (elemento_id)
        REFERENCES elemento_proceso (id) ON DELETE CASCADE,
    CONSTRAINT ck_gateway_tipo CHECK (
        tipo_gateway IN ('EXCLUSIVO', 'PARALELO', 'INCLUSIVO')
    )
);

CREATE TABLE arco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id BIGINT NOT NULL,
    origen_id BIGINT NOT NULL,
    destino_id BIGINT NOT NULL,
    etiqueta VARCHAR(150),
    condicion TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_arco_proceso FOREIGN KEY (proceso_id)
        REFERENCES proceso (id) ON DELETE CASCADE,
    CONSTRAINT fk_arco_origen FOREIGN KEY (origen_id)
        REFERENCES elemento_proceso (id) ON DELETE CASCADE,
    CONSTRAINT fk_arco_destino FOREIGN KEY (destino_id)
        REFERENCES elemento_proceso (id) ON DELETE CASCADE,
    CONSTRAINT ck_arco_sin_autoarco CHECK (origen_id <> destino_id),
    CONSTRAINT uk_arco_proceso_extremos
        UNIQUE (proceso_id, origen_id, destino_id)
);

CREATE INDEX ix_arco_origen ON arco (origen_id);
CREATE INDEX ix_arco_destino ON arco (destino_id);

CREATE TABLE mensaje (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id BIGINT NOT NULL,
    pool_origen_id BIGINT NOT NULL,
    pool_destino_id BIGINT NOT NULL,
    elemento_origen_id BIGINT,
    elemento_destino_id BIGINT,
    nombre VARCHAR(150) NOT NULL,
    clave_correlacion VARCHAR(150) NOT NULL,
    politica_sin_correspondencia VARCHAR(500),
    politica_fallo VARCHAR(500),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_mensaje_proceso FOREIGN KEY (proceso_id)
        REFERENCES proceso (id) ON DELETE CASCADE,
    CONSTRAINT fk_mensaje_pool_origen FOREIGN KEY (pool_origen_id, proceso_id)
        REFERENCES pool (id, proceso_id) ON DELETE CASCADE,
    CONSTRAINT fk_mensaje_pool_destino FOREIGN KEY (pool_destino_id, proceso_id)
        REFERENCES pool (id, proceso_id) ON DELETE CASCADE,
    CONSTRAINT fk_mensaje_elemento_origen FOREIGN KEY (
        elemento_origen_id, proceso_id, pool_origen_id
    ) REFERENCES elemento_proceso (id, proceso_id, pool_id) ON DELETE RESTRICT,
    CONSTRAINT fk_mensaje_elemento_destino FOREIGN KEY (
        elemento_destino_id, proceso_id, pool_destino_id
    ) REFERENCES elemento_proceso (id, proceso_id, pool_id) ON DELETE RESTRICT,
    CONSTRAINT ck_mensaje_pools_distintos CHECK (pool_origen_id <> pool_destino_id),
    CONSTRAINT ck_mensaje_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_mensaje_correlacion_no_vacia CHECK (btrim(clave_correlacion) <> '')
);

CREATE INDEX ix_mensaje_proceso ON mensaje (proceso_id);
CREATE INDEX ix_mensaje_pool_origen ON mensaje (pool_origen_id);
CREATE INDEX ix_mensaje_pool_destino ON mensaje (pool_destino_id);

CREATE TABLE campo_mensaje (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje_id BIGINT NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    tipo_dato VARCHAR(50) NOT NULL,
    descripcion VARCHAR(500),
    obligatorio BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_campo_mensaje FOREIGN KEY (mensaje_id)
        REFERENCES mensaje (id) ON DELETE CASCADE,
    CONSTRAINT ck_campo_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_campo_tipo_no_vacio CHECK (btrim(tipo_dato) <> ''),
    CONSTRAINT uk_campo_mensaje_nombre UNIQUE (mensaje_id, nombre)
);

CREATE INDEX ix_campo_mensaje ON campo_mensaje (mensaje_id);

-- Reglas que necesitan consultar varias tablas.
CREATE OR REPLACE FUNCTION validar_relaciones_bpmn()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    empresa_proceso BIGINT;
    empresa_usuario BIGINT;
    empresa_rol BIGINT;
    empresa_participante BIGINT;
    pool_origen BIGINT;
    pool_destino BIGINT;
BEGIN
    IF TG_TABLE_NAME = 'historial_proceso' THEN
        SELECT p.empresa_id, u.empresa_id
          INTO empresa_proceso, empresa_usuario
          FROM proceso p, usuario u
         WHERE p.id = NEW.proceso_id AND u.id = NEW.usuario_id;
        IF empresa_proceso IS DISTINCT FROM empresa_usuario THEN
            RAISE EXCEPTION 'El usuario del historial debe pertenecer a la empresa propietaria del proceso';
        END IF;
    ELSIF TG_TABLE_NAME = 'proceso_compartido' THEN
        SELECT p.empresa_id, u.empresa_id
          INTO empresa_proceso, empresa_usuario
          FROM proceso p, usuario u
         WHERE p.id = NEW.proceso_id AND u.id = NEW.autorizado_por_id;
        IF empresa_proceso IS DISTINCT FROM empresa_usuario THEN
            RAISE EXCEPTION 'Quien comparte debe pertenecer a la empresa propietaria del proceso';
        END IF;
        IF empresa_proceso = NEW.empresa_invitada_id THEN
            RAISE EXCEPTION 'Una empresa no puede invitarse a su propio proceso';
        END IF;
    ELSIF TG_TABLE_NAME IN ('lane', 'pool_rol_disponible') THEN
        SELECT rp.empresa_id, po.empresa_participante_id
          INTO empresa_rol, empresa_participante
          FROM rol_proceso rp, pool po
         WHERE rp.id = NEW.rol_proceso_id AND po.id = NEW.pool_id;
        IF empresa_participante IS NULL OR empresa_rol IS DISTINCT FROM empresa_participante THEN
            RAISE EXCEPTION 'El rol debe pertenecer a la empresa participante del pool';
        END IF;
    ELSIF TG_TABLE_NAME = 'actividad' THEN
        IF NOT EXISTS (
            SELECT 1 FROM elemento_proceso e
             WHERE e.id = NEW.elemento_id AND e.lane_id IS NOT NULL
        ) THEN
            RAISE EXCEPTION 'Toda actividad debe pertenecer exactamente a una lane';
        END IF;
        IF EXISTS (SELECT 1 FROM evento WHERE elemento_id = NEW.elemento_id)
           OR EXISTS (SELECT 1 FROM gateway WHERE elemento_id = NEW.elemento_id) THEN
            RAISE EXCEPTION 'Un elemento solo puede tener un subtipo BPMN';
        END IF;
    ELSIF TG_TABLE_NAME = 'evento' THEN
        IF EXISTS (SELECT 1 FROM actividad WHERE elemento_id = NEW.elemento_id)
           OR EXISTS (SELECT 1 FROM gateway WHERE elemento_id = NEW.elemento_id) THEN
            RAISE EXCEPTION 'Un elemento solo puede tener un subtipo BPMN';
        END IF;
    ELSIF TG_TABLE_NAME = 'gateway' THEN
        IF EXISTS (SELECT 1 FROM actividad WHERE elemento_id = NEW.elemento_id)
           OR EXISTS (SELECT 1 FROM evento WHERE elemento_id = NEW.elemento_id) THEN
            RAISE EXCEPTION 'Un elemento solo puede tener un subtipo BPMN';
        END IF;
    ELSIF TG_TABLE_NAME = 'arco' THEN
        SELECT eo.pool_id, ed.pool_id
          INTO pool_origen, pool_destino
          FROM elemento_proceso eo, elemento_proceso ed
         WHERE eo.id = NEW.origen_id
           AND ed.id = NEW.destino_id
           AND eo.proceso_id = NEW.proceso_id
           AND ed.proceso_id = NEW.proceso_id;
        IF pool_origen IS NULL OR pool_destino IS NULL OR pool_origen <> pool_destino THEN
            RAISE EXCEPTION 'Los extremos de un arco deben pertenecer al mismo proceso y pool';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_historial_empresa
BEFORE INSERT OR UPDATE ON historial_proceso
FOR EACH ROW EXECUTE FUNCTION validar_relaciones_bpmn();

CREATE TRIGGER tr_compartido_empresas
BEFORE INSERT OR UPDATE ON proceso_compartido
FOR EACH ROW EXECUTE FUNCTION validar_relaciones_bpmn();

CREATE TRIGGER tr_lane_empresa_rol
BEFORE INSERT OR UPDATE ON lane
FOR EACH ROW EXECUTE FUNCTION validar_relaciones_bpmn();

CREATE TRIGGER tr_pool_rol_empresa
BEFORE INSERT OR UPDATE ON pool_rol_disponible
FOR EACH ROW EXECUTE FUNCTION validar_relaciones_bpmn();

CREATE TRIGGER tr_actividad_lane_subtipo
BEFORE INSERT OR UPDATE ON actividad
FOR EACH ROW EXECUTE FUNCTION validar_relaciones_bpmn();

CREATE TRIGGER tr_evento_subtipo
BEFORE INSERT OR UPDATE ON evento
FOR EACH ROW EXECUTE FUNCTION validar_relaciones_bpmn();

CREATE TRIGGER tr_gateway_subtipo
BEFORE INSERT OR UPDATE ON gateway
FOR EACH ROW EXECUTE FUNCTION validar_relaciones_bpmn();

CREATE TRIGGER tr_arco_mismo_pool
BEFORE INSERT OR UPDATE ON arco
FOR EACH ROW EXECUTE FUNCTION validar_relaciones_bpmn();

COMMENT ON SCHEMA public IS
    'Persistencia del editor BPMN multiempresa; el sistema modela procesos y no los ejecuta.';
